[package]
name = "metrics-prometheus"
version = "0.1.0"
edition = "2021"
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
license = "BlueOak-1.0.0"

[dependencies]
arc-swap = "1.5"
metrics = { version = "0.20", default-features = false }
metrics-util = { version = "0.14", features = ["registry"], default-features = false }
prometheus = { version = "0.13", default-features = false }
sealed = "0.4"
smallvec = "1.10"
