[package]
name = "metrics-prometheus"
version = "0.3.1"
edition = "2021"
rust-version = "1.65"
description = "`prometheus` backend for `metrics` crate."
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
license = "BlueOak-1.0.0"
documentation = "https://docs.rs/metrics-prometheus"
homepage = "https://github.com/instrumentisto/metrics-prometheus-rs"
repository = "https://github.com/instrumentisto/metrics-prometheus-rs"
readme = "README.md"
keywords = ["metrics", "prometheus"]
categories = ["development-tools::debugging"]
include = ["/src/", "/CHANGELOG.md", "/LICENSE.md", "/README.md"]

[dependencies]
arc-swap = "1.5"
metrics = { version = "0.20", default-features = false }
metrics-util = { version = "0.15", features = ["registry"], default-features = false }
once_cell = "1.16"
prometheus = { version = "0.13", default-features = false }
sealed = "0.4"
smallvec = "1.10"

# Not realy used, for surviving MSRV check only.
# TODO: Fix in `prometheus` crate.
thiserror = "1.0.2"

[dev-dependencies]
metrics-util = { version = "0.15", features = ["layer-filter"], default-features = false }
